types: [
  'CruiseControlProject',
  'JenkinsProject',
  'SemaphoreProject',
  'TeamCityRestProject',
  'TeamCityProject',
  'TravisProject',
  'TravisProProject',
  'TddiumProject',
  'CircleCiProject',
  'ConcourseV1Project',
  'ConcourseProject',
  'CodeshipProject',
]

labels:
  ci_build_identifier:
    team_city_rest_project: "Build Type ID"
    team_city_project: "Build ID"
    tddium_project: "Tddium Project Name"
    concourse_v1_project: "Job Name"
    concourse_project: "Job Name"
    codeship_project: "Project ID"
  ci_auth_token:
    tddium_project: "Tddium Authentication Token"
  concourse_pipeline_name:
    concourse_v1_project: "Pipeline Name"
    concourse_project: "Pipeline Name"

tooltips:
  ci_auth_token:
    travis_pro_project: "Find this on your Travis-CI.com profile"
  ci_build_identifier:
    tddium_project: "Project name format: 'repo_name (branch_name)'"
    codeship_project: "Found in the URL when viewing your Codeship project: 'https://www.codeship.io/projects/%your-project-ID%'"
